### ISSUE TITLE
Which paper to cite if we use the parser?

### ISSUE THREAD

**Issue by yekeren** [vacancy/SceneGraphParser#13]
Thanks for the work! May I ask which paper (besides schuster et al.) should we cite if we use the parser in our work?

**Comment by vacancy** [comment]
This repo was developed for

Unified Visual-Semantic Embeddings: Bridging Vision and Language With Structured Meaning Representations.
Hao Wu, Jiayuan Mao, Yufeng Zhang, Yuning Jiang, Lei Li, Weiwei Sun, Wei-Ying Ma
CVPR2019

Feel free to cite (or not cite) our paper :)
The difference between this repo and the Schuster et al. can be found in #7.

**Comment by yekeren** [comment]
Thanks!
