### ISSUE TITLE
Failure cases

### ISSUE THREAD

**Issue by AleDella** [vacancy/SceneGraphParser#20]
Hi! FIrst of all I want to thank you for your hard work in developing this library! I am using it to generate graphs from captions, and I noticed that sometimes doesn't detect any relation between nouns; for example in 'many planes are parked next to a long building in an airport' the only relation detected is 'building in airport' and completely ignores the fact that planes are parked in the airport.

Thank you again for the hard work!

**Comment by zhuang-li** [comment]
@AleDella Hi, our new scene graph parser can well handle such a situation. The work has been published in ACL 2023. Welcome to have a try. https://github.com/zhuang-li/FACTUAL
